# Used for non_VS-Code environemtns. 
# Creates a container off the shared dev image and runs it.

version: "3.9"

services:
  api:
    image: ghcr.io/hallboard-team/dotnet-v${DOTNET_VERSION:-9.0}:latest
    container_name: ${CONTAINER_NAME}

    user: "0:0"
    working_dir: /workspaces/app

    volumes:
      - ../:/workspaces/app:Z
      - ~/.cache/vscode-server-shared:/home/vscode/.vscode-server-shared:Z

    environment:
      - VSCODE_SERVER_DIR=/home/vscode/.vscode-server-shared

    ports:
      - "${PORT:-5000}:5000"

    command: >
      bash -c "
        dotnet --info &&
        sleep infinity
      "
